"""
Markdown Report Generator for FSL Research Framework.
Formats comprehensive research reports including executive summary, metrics tables, and observations.
"""

from typing import Dict, Any, List
from reports.schema import ResearchReportPayload
from utilities.logger import get_logger

logger = get_logger("markdown_report_generator")


class MarkdownReportGenerator:
    """Generator formatting complete Markdown research documents."""

    @classmethod
    def generate_markdown(cls, payload: ResearchReportPayload) -> str:
        """
        Formats complete Markdown report document.
        """
        exp_id = payload.experiment_id

        md_lines = [
            f"# Comprehensive Research Report: Few-Shot Learning Evaluation",
            f"**Experiment ID**: `{exp_id}`  ",
            f"**Generated**: `{payload.timestamp}`  ",
            f"**Status**: `Completed`  ",
            "",
            "---",
            "",
            "## 1. Executive Summary",
            payload.experiment_summary,
            "",
            "> [!NOTE]",
            "> This automated report synthesizes task performance metrics, system efficiency profiles, multi-trial reliability, and statistical significance analysis.",
            "",
            "## 2. Performance Evaluation Breakdown",
            "### Task Performance Metrics",
            cls._format_dict_as_markdown_table(payload.performance_report, key_header="Metric Name", val_header="Score"),
            "",
            "## 3. Evaluation Data Tables",
            payload.evaluation_tables_md if payload.evaluation_tables_md else "_No detailed sample tables available._",
            "",
            "## 4. System Efficiency & Cost Profile",
            cls._format_dict_as_markdown_table(payload.statistical_report.get("efficiency", {}), key_header="Efficiency Metric", val_header="Value"),
            "",
            "## 5. Reliability & Trial Stability Analysis",
            cls._format_dict_as_markdown_table(payload.statistical_report.get("reliability", {}), key_header="Reliability Metric", val_header="Value"),
            "",
            "## 6. Statistical Significance & Hypothesis Testing",
            cls._format_hypothesis_tests(payload.statistical_report.get("hypothesis_tests", [])),
            "",
            "## 7. Comparative Factor Breakdown",
            cls._format_comparison_matrix(payload.comparison_report),
            "",
            "## 8. Key Research Observations & Takeaways",
        ]

        if payload.research_observations:
            for obs in payload.research_observations:
                md_lines.append(f"- {obs}")
        else:
            md_lines.append("- _No specific anomalies or observations detected during execution._")

        md_lines.extend([
            "",
            "---",
            "*Report automatically generated by the Few-Shot Learning Research Framework.*",
        ])

        report_text = "\n".join(md_lines) + "\n"
        logger.info(f"Generated Markdown Report for Experiment '{exp_id}' ({len(report_text)} chars).")
        return report_text

    @staticmethod
    def _format_dict_as_markdown_table(d: Dict[str, Any], key_header: str, val_header: str) -> str:
        """Formats a simple key-value dictionary as a Markdown table."""
        if not d:
            return "_No metrics available._\n"
        lines = [
            f"| {key_header} | {val_header} |",
            "| :--- | :--- |",
        ]
        for k, v in d.items():
            formatted_k = str(k).replace("_", " ").title()
            formatted_v = f"{v:.4f}" if isinstance(v, float) else str(v)
            lines.append(f"| {formatted_k} | `{formatted_v}` |")
        return "\n".join(lines) + "\n"

    @staticmethod
    def _format_hypothesis_tests(tests: List[Dict[str, Any]]) -> str:
        """Formats list of statistical hypothesis tests into Markdown."""
        if not tests:
            return "_Statistical testing not applicable (insufficient factor levels in single experiment)._\n"
        lines = [
            "| Test Name | Test Statistic | P-Value | Significant (p < 0.05) | Cohen's d | Interpretation |",
            "| :--- | :--- | :--- | :--- | :--- | :--- |",
        ]
        for t in tests:
            sig_str = "✓ **YES**" if t.get("is_significant") else "✗ NO"
            lines.append(
                f"| {t.get('test_name')} | `{t.get('statistic'):.4f}` | `{t.get('p_value'):.6f}` | {sig_str} | `{t.get('effect_size_cohens_d', 0.0):.2f}` | {t.get('interpretation')} |"
            )
        return "\n".join(lines) + "\n"

    @staticmethod
    def _format_comparison_matrix(comp: Dict[str, List[Dict[str, Any]]]) -> str:
        """Formats comparative factor matrix into Markdown tables."""
        if not comp:
            return "_No factor comparisons available._\n"
        lines = []
        for factor, levels in comp.items():
            lines.append(f"#### Factor: `{factor.replace('_', ' ').title()}`")
            lines.append("| Factor Level | Mean Score | Median | Std Dev | Sample Count |")
            lines.append("| :--- | :--- | :--- | :--- | :--- |")
            for lvl in levels:
                lines.append(
                    f"| **{lvl.get('level')}** | `{lvl.get('mean'):.4f}` | `{lvl.get('median'):.4f}` | `{lvl.get('std_dev'):.4f}` | `{lvl.get('count')}` |"
                )
            lines.append("")
        return "\n".join(lines) + "\n"
